name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      # Free Disk Space
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4.1.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

      # Create Tag
      - uses: phish108/autotag-action@v1.1.55
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Making-Games-${{ steps.tagger.outputs.new-tag }}-win-x64
          path: build

      # Download the artifact from the previous job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Making-Games-${{ steps.tagger.outputs.new-tag }}-win-x64

      # Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.tagger.outputs.new-tag }}
          files: |
            ./Making-Games-${{ steps.tagger.outputs.new-tag }}-win-x64/** 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
